### ISSUE TITLE
`-i` and `--input` option with no source supplied crashes the tool

### ISSUE THREAD

**Issue by SerpentBytes** [Myrfion/izyum#1]
## Environment Information

Operation System: macOS Monterey
Node version: v16.17.0

## Bug Description

Running the tool with the `-i` or `--input` option with no source file or directory supplied crashes it. 

Running with `-i`:

```
[Error: ENOENT: no such file or directory, scandir ''] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: ''
}
```
Running with `--input`:

```
node:internal/fs/utils:347
    throw err;
    ^

Error: ENOENT: no such file or directory, open
    at Object.openSync (node:fs:594:3)
    at Object.readFileSync (node:fs:462:35)
    at getFileContent (/OSD600/repos/izyum-fork/bin/index.js:106:32)
    at proccessTextFile (/OSD600/repos/izyum-fork/bin/index.js:75:25)
    at proccessSingleFile (/OSD600/repos/izyum-fork/bin/index.js:85:5)
    at Object.<anonymous> (/OSD600/repos/izyum-fork/bin/index.js:120:9)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT'
}

```

**Comment by Myrfion** [comment]
Fix in #8
